### ISSUE TITLE
Hi! Some error

### ISSUE THREAD

**Issue by yanrising** [marcelooblan2016/crypto-bot-trader#32]
After setup and installation the following happens:
Maetamask run ok, import private key is ok, matic token added ok, but dont add USDC token and i have error:

Running tests on MetaMask version v10.1.1

Setup metamask...
Adding new networks...
Adding network: matic-mainnet
Switch network: matic-mainnet
Import Tokens...
Adding matic token ...
TimeoutError: waiting for XPath `//button[contains(text(), 'Next')][not(@disabled)]` failed: timeout 30000ms exceeded
    at new WaitTask (C:\Polygon_trade_bot\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:526:34)
    at DOMWorld.waitForXPath (C:\Polygon_trade_bot\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:457:26)
    at Frame.waitForXPath (C:\Polygon_trade_bot\node_modules\puppeteer\lib\cjs\puppeteer\common\FrameManager.js:948:51)
    at Page.waitForXPath (C:\Polygon_trade_bot\node_modules\puppeteer\lib\cjs\puppeteer\common\Page.js:2410:33)
    at Object.<anonymous> (C:\Polygon_trade_bot\node_modules\crypto-bot-trader\dist\Metamask\Libs\loadTokenContracts.js:68:28)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Polygon_trade_bot\node_modules\crypto-bot-trader\dist\Metamask\Libs\loadTokenContracts.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Analyzing market...
TimeoutError: waiting for selector `.list-item.asset-list-item.token-cell` failed: timeout 15000ms exceeded
    at new WaitTask (C:\Polygon_trade_bot\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:526:34)
    at DOMWorld.waitForSelectorInPage (C:\Polygon_trade_bot\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:430:26)
    at Object.internalHandler.waitFor (C:\Polygon_trade_bot\node_modules\puppeteer\lib\cjs\puppeteer\common\QueryHandler.js:31:77)
    at DOMWorld.waitForSelector (C:\Polygon_trade_bot\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:321:29)
    at Frame.waitForSelector (C:\Polygon_trade_bot\node_modules\puppeteer\lib\cjs\puppeteer\common\FrameManager.js:924:51)
    at Page.waitForSelector (C:\Polygon_trade_bot\node_modules\puppeteer\lib\cjs\puppeteer\common\Page.js:2359:33)
    at C:\Polygon_trade_bot\node_modules\crypto-bot-trader\dist\Metamask\Libs\getBalances.js:86:24
    at Generator.next (<anonymous>)
    at fulfilled (C:\Polygon_trade_bot\node_modules\crypto-bot-trader\dist\Metamask\Libs\getBalances.js:5:58)
Home modal found.
Analyzing market...
TimeoutError: waiting for selector `.list-item.asset-list-item.token-cell` failed: timeout 15000ms exceeded
    at new WaitTask (C:\Polygon_trade_bot\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:526:34)
    at DOMWorld.waitForSelectorInPage (C:\Polygon_trade_bot\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:430:26)
    at Object.internalHandler.waitFor (C:\Polygon_trade_bot\node_modules\puppeteer\lib\cjs\puppeteer\common\QueryHandler.js:31:77)
    at DOMWorld.waitForSelector (C:\Polygon_trade_bot\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:321:29)
    at Frame.waitForSelector (C:\Polygon_trade_bot\node_modules\puppeteer\lib\cjs\puppeteer\common\FrameManager.js:924:51)
    at Page.waitForSelector (C:\Polygon_trade_bot\node_modules\puppeteer\lib\cjs\puppeteer\common\Page.js:2359:33)
    at C:\Polygon_trade_bot\node_modules\crypto-bot-trader\dist\Metamask\Libs\getBalances.js:86:24
    at Generator.next (<anonymous>)
    at fulfilled (C:\Polygon_trade_bot\node_modules\crypto-bot-trader\dist\Metamask\Libs\getBalances.js:5:58)
Home modal found.
Analyzing market...
TimeoutError: waiting for selector `.list-item.asset-list-item.token-cell` failed: timeout 15000ms exceeded
    at new WaitTask (C:\Polygon_trade_bot\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:526:34)
    at DOMWorld.waitForSelectorInPage (C:\Polygon_trade_bot\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:430:26)
    at Object.internalHandler.waitFor (C:\Polygon_trade_bot\node_modules\puppeteer\lib\cjs\puppeteer\common\QueryHandler.js:31:77)
    at DOMWorld.waitForSelector (C:\Polygon_trade_bot\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:321:29)
    at Frame.waitForSelector (C:\Polygon_trade_bot\node_modules\puppeteer\lib\cjs\puppeteer\common\FrameManager.js:924:51)
    at Page.waitForSelector (C:\Polygon_trade_bot\node_modules\puppeteer\lib\cjs\puppeteer\common\Page.js:2359:33)
    at C:\Polygon_trade_bot\node_modules\crypto-bot-trader\dist\Metamask\Libs\getBalances.js:86:24
    at Generator.next (<anonymous>)
    at fulfilled (C:\Polygon_trade_bot\node_modules\crypto-bot-trader\dist\Metamask\Libs\getBalances.js:5:58)

At this step I add USDC token manually and script continues to work:

Analyzing market...
Market Analyzed.
Analyzing market...
Market Analyzed.
Analyzing market...
Market Analyzed.

Is this a critical error? Maybe I did something wrong? 
OS Windows 10, node v16.13.1, all depencies (crypto-bot-trader, puppeteer etc.) installed correctly)

**Comment by marcelooblan2016** [comment]
> After setup and installation the following happens: Maetamask run ok, import private key is ok, matic token added ok, but dont add USDC token and i have error:
> 
> Running tests on MetaMask version v10.1.1
> 
> Setup metamask... Adding new networks... Adding network: matic-mainnet Switch network: matic-mainnet Import Tokens... Adding matic token ... TimeoutError: waiting for XPath `//button[contains(text(), 'Next')][not(@disabled)]` failed: timeout 30000ms exceeded at new WaitTask (C:\Polygon_trade_bot\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:526:34) at DOMWorld.waitForXPath (C:\Polygon_trade_bot\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:457:26) at Frame.waitForXPath (C:\Polygon_trade_bot\node_modules\puppeteer\lib\cjs\puppeteer\common\FrameManager.js:948:51) at Page.waitForXPath (C:\Polygon_trade_bot\node_modules\puppeteer\lib\cjs\puppeteer\common\Page.js:2410:33) at Object. (C:\Polygon_trade_bot\node_modules\crypto-bot-trader\dist\Metamask\Libs\loadTokenContracts.js:68:28) at Generator.next () at fulfilled (C:\Polygon_trade_bot\node_modules\crypto-bot-trader\dist\Metamask\Libs\loadTokenContracts.js:5:58) at runMicrotasks () at processTicksAndRejections (node:internal/process/task_queues:96:5) Analyzing market... TimeoutError: waiting for selector `.list-item.asset-list-item.token-cell` failed: timeout 15000ms exceeded at new WaitTask (C:\Polygon_trade_bot\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:526:34) at DOMWorld.waitForSelectorInPage (C:\Polygon_trade_bot\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:430:26) at Object.internalHandler.waitFor (C:\Polygon_trade_bot\node_modules\puppeteer\lib\cjs\puppeteer\common\QueryHandler.js:31:77) at DOMWorld.waitForSelector (C:\Polygon_trade_bot\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:321:29) at Frame.waitForSelector (C:\Polygon_trade_bot\node_modules\puppeteer\lib\cjs\puppeteer\common\FrameManager.js:924:51) at Page.waitForSelector (C:\Polygon_trade_bot\node_modules\puppeteer\lib\cjs\puppeteer\common\Page.js:2359:33) at C:\Polygon_trade_bot\node_modules\crypto-bot-trader\dist\Metamask\Libs\getBalances.js:86:24 at Generator.next () at fulfilled (C:\Polygon_trade_bot\node_modules\crypto-bot-trader\dist\Metamask\Libs\getBalances.js:5:58) Home modal found. Analyzing market... TimeoutError: waiting for selector `.list-item.asset-list-item.token-cell` failed: timeout 15000ms exceeded at new WaitTask (C:\Polygon_trade_bot\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:526:34) at DOMWorld.waitForSelectorInPage (C:\Polygon_trade_bot\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:430:26) at Object.internalHandler.waitFor (C:\Polygon_trade_bot\node_modules\puppeteer\lib\cjs\puppeteer\common\QueryHandler.js:31:77) at DOMWorld.waitForSelector (C:\Polygon_trade_bot\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:321:29) at Frame.waitForSelector (C:\Polygon_trade_bot\node_modules\puppeteer\lib\cjs\puppeteer\common\FrameManager.js:924:51) at Page.waitForSelector (C:\Polygon_trade_bot\node_modules\puppeteer\lib\cjs\puppeteer\common\Page.js:2359:33) at C:\Polygon_trade_bot\node_modules\crypto-bot-trader\dist\Metamask\Libs\getBalances.js:86:24 at Generator.next () at fulfilled (C:\Polygon_trade_bot\node_modules\crypto-bot-trader\dist\Metamask\Libs\getBalances.js:5:58) Home modal found. Analyzing market... TimeoutError: waiting for selector `.list-item.asset-list-item.token-cell` failed: timeout 15000ms exceeded at new WaitTask (C:\Polygon_trade_bot\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:526:34) at DOMWorld.waitForSelectorInPage (C:\Polygon_trade_bot\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:430:26) at Object.internalHandler.waitFor (C:\Polygon_trade_bot\node_modules\puppeteer\lib\cjs\puppeteer\common\QueryHandler.js:31:77) at DOMWorld.waitForSelector (C:\Polygon_trade_bot\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:321:29) at Frame.waitForSelector (C:\Polygon_trade_bot\node_modules\puppeteer\lib\cjs\puppeteer\common\FrameManager.js:924:51) at Page.waitForSelector (C:\Polygon_trade_bot\node_modules\puppeteer\lib\cjs\puppeteer\common\Page.js:2359:33) at C:\Polygon_trade_bot\node_modules\crypto-bot-trader\dist\Metamask\Libs\getBalances.js:86:24 at Generator.next () at fulfilled (C:\Polygon_trade_bot\node_modules\crypto-bot-trader\dist\Metamask\Libs\getBalances.js:5:58)
> 
> At this step I add USDC token manually and script continues to work:
> 
> Analyzing market... Market Analyzed. Analyzing market... Market Analyzed. Analyzing market... Market Analyzed.
> 
> Is this a critical error? Maybe I did something wrong? OS Windows 10, node v16.13.1, all depencies (crypto-bot-trader, puppeteer etc.) installed correctly)

Hello, i just finished the fixes for windows users; can you try updating your package into: "1.0.45"; do the "npm install" again for updates.
Let me know how it works.
Best regards,

**Comment by yanrising** [comment]
Thanks!
